### ISSUE TITLE
Error running on EMR with Spark version 2.4.0 and Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_265)

### ISSUE THREAD

**Issue by leontp587** [qubole/s3-sqs-connector#7]
Hello,

This library looks very promising, but I cannot run it successfully on AWS EMR.

**app.scala:**
import org.apache.spark.sql.types.StructType

val inputDf = spark 
 .readStream
 .format("s3-sqs")
 .schema(new StructType().add("name", "string"))
 .option("sqsUrl", "https://sqs.us-east-1.amazonaws.com/561461140170/s3-spark-streaming")
 .option("region", "us-east-1")
 .option("fileFormat", "csv")
 .option("sqsFetchIntervalSeconds", "2")
 .option("useInstanceProfileCredentials", "true")
 .option("sqsLongPollingWaitTimeSeconds", "5")
 .load()

val c = inputDf.select("*")

val query = c
    .writeStream
    .outputMode("append")
    .format("console")
    .start()

query.awaitTermination()

I ran:
spark-shell --packages com.qubole:spark-sql-streaming-sqs_2.11:0.5.1 -i app.scala

Once the first file is uploaded to S3, the library fails:

20/11/09 04:06:54 ERROR MicroBatchExecution: Query [id = 1c453f25-4de5-48f9-9262-63b33a14cf2d, runId = ad1b7d57-513c-4942-bf65-7386224d4c68] terminated with error
java.lang.NoSuchMethodError: org.apache.spark.sql.Dataset$.ofRows$default$3()Ljava/lang/String;
        at org.apache.spark.sql.streaming.sqs.SqsSource.getBatch(SqsSource.scala:80)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$10.apply(MicroBatchExecution.scala:438)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3$$anonfun$apply$10.apply(MicroBatchExecution.scala:434)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at org.apache.spark.sql.execution.streaming.StreamProgress.flatMap(StreamProgress.scala:25)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:434)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$3.apply(MicroBatchExecution.scala:434)

**Comment by leontp587** [comment]
Duplicate to https://github.com/qubole/s3-sqs-connector/issues/1
